import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const app = await readFile(new URL("./app.js", import.meta.url), "utf8");

// A real browser remains necessary for final learner observation. These
// checks keep the declared interaction paths from disappearing in refactors.
for (const required of [
  'function cancelPendingInteraction(',
  'document.addEventListener("keydown"',
  'event.key !== "Escape"',
  'anchor.addEventListener("keydown"',
  'event.key !== "Enter" && event.key !== " "',
  'await proposePinConnection(start, end);',
  'if (command === "cancel route")',
  'Component source and Board picture are unchanged.',
  'vectors.classList.add("board-vectors")',
  'function drawLabels(vectors)',
  'function beginLabel(position, existing = null)',
  'label-inline-editor',
  'editor.contentEditable = "true"',
  'editor.addEventListener("blur"',
  'Click elsewhere to save',
  'text.addEventListener("dblclick"',
  'if (isLabelTool()) { beginLabel(label.position, label); return; }',
  'function isLabelTool()',
  'suppressNextLabelClick',
  'Drag to move it, drag its corner handle to resize, double-click to edit',
  'label-resize-handle',
  'kind: "label-resize"',
  'label-color-palette',
  'LABEL_COLOR_PALETTE.forEach(color',
  'property-label-color-code',
  'createBoardProfileV2',
  'migrateBoardProfileV1ToV2',
  'validateBoardProfileV2',
  'checkedWorldPoint(world)',
  'LEGACY_BOARD_PROFILE_KEY',
  'zoomViewportAt(ensureViewport(canvas)',
  'panViewport(ensureViewport(canvas)',
  'View moved. Component source and Board picture are unchanged.',
  'Left-drag any device, net, route bend, or label',
  'endpointScreenPoint',
  'function shouldShowWire(wire)',
  'state.guideVisibleEdges.includes(edgeId(wire))',
  'createGuideToggleOperation({ focus, topology:',
  'applyGuideToggleOperation(operation, { wires:',
  'component:operation ${operation.kind} ${operation.id}',
  'function isGuideTool()',
  'anchor.addEventListener("click"',
  'anchor.dataset.pinGestureBound',
  'nodes.forEach(node => drawNode(canvas, node));',
  'installPinGesture();',
  'previousChildren',
  'function drawBorderFrame(canvas, node)',
  'function genericAnchorMarkup(node)',
  'node-anchor-layer',
  'toggleGuideFocus({ kind: node.kind, id: node.id })',
  'if (isGuideTool()) {',
  '$("#board-canvas").classList.toggle("guide-mode", tool === "guide")',
  'function toggleGuideFocus(focus)',
  'Hid all ${change.edgeCount} routing guide',
  'Click another endpoint to toggle one guide',
  'Connect node ${anchor.endpoint}',
  'openObjectProperties(event, { title: "Label properties"',
  'text.addEventListener("contextmenu"',
  'edge.addEventListener("contextmenu"',
  'anchor.addEventListener("contextmenu"',
  'Route bend properties',
  '$("#board-canvas").addEventListener("contextmenu"',
  'LABEL_COLOR_PALETTE',
  'property-label-bold',
  'Double-click the label itself to edit text',
]) assert.ok(app.includes(required), `missing interaction contract: ${required}`);

assert.ok(!app.includes("projectLegacyPoint"), "Board renderer must not retain the v1 coordinate adapter");
assert.ok(!app.includes(".getBBox()"), "Selected labels must not depend on browser SVG layout measurement after the viewport is cleared");

console.log("Board interaction contract checks passed");
