#!/usr/bin/env python3
"""Cross-check active-low pin polarity between DB definitions and Python models."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "POLARITY_CROSSCHECK_REPORT.md"
sys.path.insert(0, str(ROOT / "python"))


DB_TO_PY_DIR = {
    "input": "in",
    "output": "out",
    "bidirectional": "bidir",
    "power": "power",
    "nc": "nc",
}


def import_model(path: Path):
    module_name = "polarity_model_" + "_".join(path.parts[-4:-2]).lower()
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def polarity_from_name(name: str) -> bool:
    return name.startswith("/")


def main() -> int:
    rows: list[dict[str, Any]] = []
    problems: list[str] = []

    for definition in sorted((ROOT / "lib" / "standard").glob("*/**/definition/definition.json")):
        group = definition.relative_to(ROOT / "lib" / "standard").parts[0]
        if group not in {"74xx", "memory"}:
            continue
        data = json.loads(definition.read_text(encoding="utf-8"))
        part = str(data.get("part") or definition.parents[1].name)
        model_path = definition.parents[1] / "simulation" / "model.py"
        if not model_path.exists():
            problems.append(f"{part}: missing simulation/model.py")
            continue
        try:
            chip = import_model(model_path).create("U")
        except Exception as exc:  # noqa: BLE001
            problems.append(f"{part}: cannot import/create Python model: {exc!r}")
            continue

        for pin in data.get("pins", []):
            number = int(pin["number"])
            db_name = str(pin["name"])
            db_dir = str(pin["direction"])
            if db_dir not in {"input", "output", "bidirectional"}:
                continue
            db_active = bool(pin.get("active_low", False))
            name_active = polarity_from_name(db_name)
            py_pin = chip.pins.get(number)
            if py_pin is None:
                add_problem(rows, problems, part, number, db_name, db_dir, "missing_python_pin")
                continue
            py_name = py_pin.name
            py_dir = py_pin.direction
            py_active = bool(py_pin.spec.active_low)
            issues = []
            if db_name != py_name:
                issues.append(f"name db={db_name!r} py={py_name!r}")
            expected_py_dir = DB_TO_PY_DIR[db_dir]
            if py_dir != expected_py_dir:
                issues.append(f"direction db={db_dir!r} py={py_dir!r}")
            if db_active != name_active:
                issues.append(f"DB active_low={db_active} but name slash={name_active}")
            if py_active != polarity_from_name(py_name):
                issues.append(f"Python active_low={py_active} but name slash={polarity_from_name(py_name)}")
            if db_active != py_active:
                issues.append(f"active_low db={db_active} py={py_active}")
            result = "PASS" if not issues else "FAIL"
            if issues:
                problems.append(f"{part} pin {number} {db_name}: " + "; ".join(issues))
            rows.append(
                {
                    "part": part,
                    "pin": number,
                    "direction": db_dir,
                    "db_name": db_name,
                    "py_name": py_name,
                    "db_active_low": db_active,
                    "py_active_low": py_active,
                    "result": result,
                    "details": "; ".join(issues) if issues else "-",
                }
            )

    write_report(rows, problems)
    print(json.dumps({"rows": len(rows), "failures": problems, "report": str(REPORT)}, indent=2))
    return 1 if problems else 0


def add_problem(
    rows: list[dict[str, Any]],
    problems: list[str],
    part: str,
    number: int,
    name: str,
    direction: str,
    detail: str,
) -> None:
    problems.append(f"{part} pin {number} {name}: {detail}")
    rows.append(
        {
            "part": part,
            "pin": number,
            "direction": direction,
            "db_name": name,
            "py_name": "-",
            "db_active_low": "",
            "py_active_low": "",
            "result": "FAIL",
            "details": detail,
        }
    )


def write_report(rows: list[dict[str, Any]], problems: list[str]) -> None:
    lines = [
        "# Polarity Cross-check Report",
        "",
        "Generated by `tools/polarity_crosscheck.py` from DB pin definitions and local Python chip models.",
        "",
        "This checks input, output, and bidirectional pins. A pin is active-low only when both the DB and Python model use a leading `/` name and matching `active_low` metadata.",
        "",
        "| Part | Pin | Direction | DB Name | Python Name | DB active_low | Python active_low | Result | Details |",
        "|---|---:|---|---|---|---:|---:|---|---|",
    ]
    for row in rows:
        lines.append(
            "| {part} | {pin} | {direction} | {db_name} | {py_name} | {db_active_low} | {py_active_low} | {result} | {details} |".format(
                **row
            )
        )
    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- Pins checked: {len(rows)}",
            f"- Failures: {len(problems)}",
            "",
            "## Failure Detail",
        ]
    )
    if problems:
        lines.extend(f"- {problem}" for problem in problems)
    else:
        lines.append("- none")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
