#!/usr/bin/env python3
"""Audit whether active physical models expose timing simulation hooks."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "Docs" / "TIMING_SIMULATION_AUDIT.md"
PHYSICAL_GROUPS = {"74xx", "Memory"}


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def group_from_path(path: Path) -> str:
    return path.relative_to(ROOT / "DB").parts[0]


def has_timing_definition(data: dict[str, Any]) -> bool:
    timing = data.get("timing")
    layer = data.get("definition_layers", {}).get("timing")
    return isinstance(timing, dict) or isinstance(layer, dict)


def simulation_manifest(part_dir: Path) -> dict[str, Any]:
    path = part_dir / "simulation" / "model.json"
    return load_json(path) if path.exists() else {}


def file_contains(path: Path, needles: tuple[str, ...]) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    return any(needle in text for needle in needles)


def python_delay_status(part_dir: Path, manifest: dict[str, Any]) -> str:
    path = part_dir / "simulation" / "model.py"
    implements = manifest.get("python", {}).get("implements", [])
    if not path.exists():
        return "missing"
    if file_contains(path, ("Delay(", "delay_ns", "self.delay")) or "propagation_delay" in implements:
        return "chip_delay"
    return "functional_only"


def verilog_delay_status(part_dir: Path, manifest: dict[str, Any]) -> str:
    path = part_dir / "simulation" / "model.v"
    implements = manifest.get("verilog", {}).get("implements", [])
    if not path.exists():
        return "missing"
    if file_contains(path, ("DELAY_RISE", "DELAY_FALL", "assign #", "#(")) or "propagation_delay" in implements:
        return "parameterized_delay"
    return "functional_only"


def netlist_delay_status(part_dir: Path) -> str:
    path = part_dir / "simulation" / "netlist.json"
    if not path.exists():
        return "missing"
    data = load_json(path)
    text = json.dumps(data, sort_keys=True)
    if "delay_ns" in text or "sample_delay_ns" in text:
        return "delay_mapped"
    return "no_delay_mapping"


def canonical_timing_status(data: dict[str, Any]) -> str:
    payload = {
        "timing": data.get("timing", {}),
        "definition_layers": {"timing": data.get("definition_layers", {}).get("timing", {})},
    }
    text = json.dumps(payload, sort_keys=True).lower()
    exact_tokens = (
        "tplh",
        "tphl",
        "tpzh",
        "tpzl",
        "tphz",
        "tplz",
        "clock_to_q_high",
        "clock_to_q_low",
        "minimum_pulse_width",
    )
    generic_tokens = (
        "tpd",
        "enable",
        "disable",
        "clock_to_q",
        "setup",
        "hold",
        "pulse",
        "delay_ns",
    )
    if any(token in text for token in exact_tokens):
        return "some_canonical"
    if any(token in text for token in generic_tokens):
        return "generic_or_default"
    return "missing"


def audit_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for definition in sorted((ROOT / "DB").glob("*/*/definition/definition.json")):
        group = group_from_path(definition)
        if group not in PHYSICAL_GROUPS:
            continue
        data = load_json(definition)
        if data.get("schema") != "db.component.digital":
            continue
        part_dir = definition.parents[1]
        manifest = simulation_manifest(part_dir)
        rows.append(
            {
                "part": str(data.get("part") or part_dir.name),
                "group": group,
                "definition_timing": "present" if has_timing_definition(data) else "missing",
                "canonical_timing": canonical_timing_status(data),
                "python_model": python_delay_status(part_dir, manifest),
                "verilog_model": verilog_delay_status(part_dir, manifest),
                "netlist": netlist_delay_status(part_dir),
            }
        )
    return rows


def count(rows: list[dict[str, str]], key: str, value: str) -> int:
    return sum(1 for row in rows if row[key] == value)


def write_report(rows: list[dict[str, str]]) -> None:
    lines = [
        "# Timing Simulation Audit",
        "",
        "Generated by `tools/timing_simulation_audit.py`.",
        "",
        "This checks active physical ICs for timing metadata and executable",
        "simulation hooks. It does not prove datasheet-accurate timing; it only",
        "confirms whether each model has a timing path instead of being purely",
        "functional.",
        "",
        "## Summary",
        "",
        f"- Rows checked: {len(rows)}",
        f"- Definitions with timing metadata: {count(rows, 'definition_timing', 'present')}",
        f"- Python models with chip-level delay hooks: {count(rows, 'python_model', 'chip_delay')}",
        f"- Verilog models with parameterized delay hooks: {count(rows, 'verilog_model', 'parameterized_delay')}",
        f"- Netlist mappings with delay fields: {count(rows, 'netlist', 'delay_mapped')}",
        f"- Definitions with some canonical timing terms: {count(rows, 'canonical_timing', 'some_canonical')}",
        f"- Definitions still generic/default timing only: {count(rows, 'canonical_timing', 'generic_or_default')}",
        "",
        "## Finding",
        "",
        "- Every active physical IC checked has timing metadata and a Python model",
        "  delay hook.",
        "- Verilog timing is parameterized for models that have Verilog files.",
        "- The simulation timing path is still chip-level or generic for most",
        "  models. It is not yet a per-parameter implementation of `tPLH`, `tPHL`,",
        "  `tPZH`, `tPZL`, `tPHZ`, `tPLZ`, clock-to-Q HIGH/LOW, setup, hold, or",
        "  minimum pulse width.",
        "",
        "## Per-Part Matrix",
        "",
        "| Part | Group | Definition Timing | Canonical Timing | Python Model | Verilog Model | Netlist |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            "| {part} | {group} | {definition_timing} | {canonical_timing} | "
            "{python_model} | {verilog_model} | {netlist} |".format(**row)
        )
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    rows = audit_rows()
    write_report(rows)
    print(f"wrote {REPORT.relative_to(ROOT)} for {len(rows)} physical IC models")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
